name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build APK
        run: echo "Starting Build Process"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Buildozer
        run: pip install buildozer cython
      - name: Build
        run: yes | buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Omega-APK
          path: bin/*.apk
